version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore:'
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: monthly
    commit-message:
      prefix: 'chore:'
    ignore:
      - dependency-name: typescript
        versions: ['7.0.x']
    groups:
      major:
        patterns: ['*']
        update-types:
          - major
      minor-patch:
        patterns: ['*']
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /test/dapp
    target-branch: main
    schedule:
      interval: monthly
    commit-message:
      prefix: 'chore:'
    groups:
      major:
        patterns: ["*"]
        update-types:
          - major
      minor-patch:
        patterns: ["*"]
        update-types:
          - minor
          - patch
