name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version: 22

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v7
        with:
          cache: pnpm
          node-version: 22

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

  integration:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.62.1-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v7
        with:
          cache: pnpm
          cache-dependency-path: |
            pnpm-lock.yaml
            test/dapp/pnpm-lock.yaml
          node-version: 22

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install dapp dependencies
        run: cd ./test/dapp && pnpm install --frozen-lockfile

      - name: Test
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pnpm run test
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: playwright-traces
          path: test-results
